export enum PATHS {
    AUTH = 'auth',
    LOGIN = 'login',
    SITES = 'sites/:site',
    ADMIN = 'admin',
    UNAUTHORIZED = 'unauthorized',
    FORGOT_PASSWORD = 'forgot-password',
    RECOVER_PASSWORD = 'recover-password',
    RESET_PASSWORD = 'reset-password',
    WELCOME_RESET_PASSWORD = 'welcome',
    HOME = 'cb',
    DAILY_DASHBOARD = 'daily-dashboard',
    WEEKLY_DASHBOARD = 'weekly-dashboard',
    FEEDBACK_LOG = 'feedback-log',
    SITE_ACCESSIBILITY = 'site-accessibility',
    USER_NOTIFICATIONS = 'user-notifications',
    USER_MANAGEMENT = 'user-management',
    SITES_ADMIN = 'sites',
    TIDE = 'tide'
}
